# Generated by Django 5.2.17 on 2026-09-28 07:24

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models

import apps.common.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=apps.common.ids.uuid7, editable=False, unique=True),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("declared_content_type", models.CharField(max_length=100)),
                ("declared_size", models.PositiveIntegerField()),
                ("detected_content_type", models.CharField(blank=True, max_length=100, null=True)),
                ("size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFYING", "Verifying"),
                            ("READY", "Ready"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=64, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="service_requests.servicerequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attachment",
                "indexes": [
                    models.Index(fields=["request", "created_at"], name="attachment_request_idx"),
                    models.Index(
                        condition=models.Q(("status__in", ["PENDING", "VERIFYING"])),
                        fields=["created_at"],
                        name="attachment_unfinished_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["PENDING", "VERIFYING", "READY", "REJECTED"])
                        ),
                        name="attachment_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("declared_size__gt", 0), ("declared_size__lte", 10485760)
                        ),
                        name="attachment_declared_size_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("size_bytes__isnull", True),
                            models.Q(("size_bytes__gt", 0), ("size_bytes__lte", 10485760)),
                            _connector="OR",
                        ),
                        name="attachment_size_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "READY"), _negated=True),
                            models.Q(
                                ("detected_content_type__isnull", False),
                                ("sha256__isnull", False),
                                ("size_bytes__isnull", False),
                                ("verified_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="attachment_ready_is_verified",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "REJECTED"), _negated=True),
                            ("rejection_reason__isnull", False),
                            _connector="OR",
                        ),
                        name="attachment_rejected_has_reason",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sha256__isnull", True),
                            ("sha256__regex", "^[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="attachment_sha256_format",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=apps.common.ids.uuid7, editable=False, unique=True),
                ),
                ("body", models.CharField(max_length=5000)),
                ("is_internal", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="service_requests.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "comment",
                "indexes": [
                    models.Index(fields=["request", "created_at"], name="comment_request_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.GreaterThan(
                            django.db.models.functions.text.Length("body"), 0
                        ),
                        name="comment_body_not_empty",
                    )
                ],
            },
        ),
    ]
