# Generated by Django 5.2.17 on 2026-09-28 07:24

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models

from apps.common.migration_ops import CreatePartitionedModel


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_seal_seq", models.BigIntegerField()),
                ("last_seal_seq", models.BigIntegerField()),
                ("last_row_hash", models.CharField(max_length=64)),
                ("object_key", models.CharField(max_length=255, unique=True)),
                ("object_version", models.CharField(blank=True, max_length=128, null=True)),
                ("stored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
            ],
            options={
                "db_table": "audit_anchor",
                "indexes": [
                    models.Index(
                        condition=models.Q(("stored_at__isnull", True)),
                        fields=["created_at"],
                        name="audit_anchor_pending_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.GreaterThanOrEqual(
                            models.F("last_seal_seq"), models.F("first_seal_seq")
                        ),
                        name="audit_anchor_range_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("last_seal_seq",), name="audit_anchor_last_seq_unique"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rule", models.CharField(max_length=32)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("observed", models.PositiveIntegerField()),
                ("threshold", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "access_alert",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "OPEN")),
                        fields=["created_at"],
                        name="access_alert_open_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["OPEN", "ACKNOWLEDGED", "DISMISSED"])),
                        name="access_alert_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("window_end__gt", models.F("window_start"))),
                        name="access_alert_window_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "OPEN"),
                            models.Q(
                                ("reviewed_at__isnull", False), ("reviewed_by__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="access_alert_reviewed_has_reviewer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reviewed_by__isnull", True),
                            models.Q(("reviewed_by", models.F("actor")), _negated=True),
                            _connector="OR",
                        ),
                        name="access_alert_no_self_review",
                    ),
                    models.UniqueConstraint(
                        fields=("actor", "rule", "window_start"),
                        name="access_alert_once_per_window",
                    ),
                ],
            },
        ),
        CreatePartitionedModel(
            name="AccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_role", models.CharField(max_length=8)),
                ("actor_department_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("UPDATE", "Update"),
                            ("DOWNLOAD", "Download"),
                            ("LIST", "List"),
                        ],
                        max_length=8,
                    ),
                ),
                ("item_count", models.PositiveIntegerField(default=1)),
                (
                    "break_glass_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUPERVISOR_REVIEW", "Supervisor Review"),
                            ("CITIZEN_COMPLAINT", "Citizen Complaint"),
                            ("AUDIT", "Audit"),
                            ("DATA_CORRECTION", "Data Correction"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("break_glass_note", models.CharField(blank=True, max_length=500, null=True)),
                ("request_uid", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service_requests.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "access_event",
                "indexes": [
                    models.Index(fields=["request", "created_at"], name="access_event_request_idx"),
                    models.Index(fields=["actor", "created_at"], name="access_event_actor_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["VIEW", "UPDATE", "DOWNLOAD", "LIST"])),
                        name="access_event_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "break_glass_reason__in",
                                [
                                    "SUPERVISOR_REVIEW",
                                    "CITIZEN_COMPLAINT",
                                    "AUDIT",
                                    "DATA_CORRECTION",
                                    "OTHER",
                                ],
                            )
                        ),
                        name="access_event_break_glass_reason_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind", "LIST"), ("request__isnull", False), _connector="OR"
                        ),
                        name="access_event_request_named",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("break_glass_reason", "OTHER"), _negated=True),
                            django.db.models.lookups.GreaterThanOrEqual(
                                django.db.models.functions.text.Length("break_glass_note"), 20
                            ),
                            _connector="OR",
                        ),
                        name="access_event_other_reason_explained",
                    ),
                ],
            },
        ),
        CreatePartitionedModel(
            name="AccessEventItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "request",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service_requests.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "access_event_item",
                "indexes": [
                    models.Index(fields=["request", "created_at"], name="access_item_request_idx")
                ],
            },
        ),
        CreatePartitionedModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_role", models.CharField(blank=True, max_length=8, null=True)),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=32)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_uid", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                ("seal_seq", models.BigIntegerField(blank=True, null=True)),
                ("prev_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("row_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("sealed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service_requests.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "indexes": [
                    models.Index(
                        condition=models.Q(("sealed_at__isnull", True)),
                        fields=["id"],
                        name="audit_log_unsealed_idx",
                    ),
                    models.Index(fields=["target_type", "target_id"], name="audit_log_target_idx"),
                    models.Index(fields=["request", "created_at"], name="audit_log_request_idx"),
                    models.Index(fields=["seal_seq"], name="audit_log_seal_seq_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("prev_hash__isnull", True),
                                ("row_hash__isnull", True),
                                ("seal_seq__isnull", True),
                                ("sealed_at__isnull", True),
                            ),
                            models.Q(
                                ("prev_hash__isnull", False),
                                ("row_hash__isnull", False),
                                ("seal_seq__isnull", False),
                                ("sealed_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="audit_log_seal_complete",
                    )
                ],
            },
        ),
    ]
