# Generated by Django 5.2.17 on 2026-09-28 07:24

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models

import apps.common.ids
from apps.common.migration_ops import CreatePartitionedModel


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreatePartitionedModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=apps.common.ids.uuid7, editable=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[("IN_APP", "In App"), ("SMS", "Sms"), ("EMAIL", "Email")],
                        max_length=8,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("STATUS", "Status"),
                            ("ACTION_REQUIRED", "Action Required"),
                            ("SECURITY", "Security"),
                        ],
                        max_length=16,
                    ),
                ),
                ("template", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("collapse_key", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("LEASED", "Leased"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SUPERSEDED", "Superseded"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("enqueued_at", models.DateTimeField(blank=True, null=True)),
                ("leased_until", models.DateTimeField(blank=True, null=True)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=32, null=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=128, null=True)),
                ("last_error", models.CharField(blank=True, max_length=500, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="service_requests.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "PENDING")),
                        fields=["next_attempt_at"],
                        name="notification_pending_idx",
                    ),
                    models.Index(
                        condition=models.Q(("status", "LEASED")),
                        fields=["leased_until"],
                        name="notification_leased_idx",
                    ),
                    models.Index(
                        condition=models.Q(("status__in", ["PENDING", "LEASED"])),
                        fields=["collapse_key", "-created_at"],
                        name="notification_collapse_idx",
                    ),
                    models.Index(
                        condition=models.Q(("channel", "IN_APP")),
                        fields=["recipient", "-created_at"],
                        name="notification_inbox_idx",
                    ),
                    models.Index(fields=["public_id"], name="notification_public_id_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("channel__in", ["IN_APP", "SMS", "EMAIL"])),
                        name="notification_channel_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["STATUS", "ACTION_REQUIRED", "SECURITY"])),
                        name="notification_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["PENDING", "LEASED", "SENT", "FAILED", "SUPERSEDED", "EXPIRED"],
                            )
                        ),
                        name="notification_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "ACTION_REQUIRED"), _negated=True),
                            ("expires_at__isnull", True),
                            _connector="OR",
                        ),
                        name="notification_action_required_never_expires",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "LEASED"), _negated=True),
                            models.Q(
                                ("lease_token__isnull", False), ("leased_until__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="notification_leased_has_lease",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempts__lte", 8)), name="notification_attempts_max"
                    ),
                ],
            },
        ),
    ]
