# Generated by Django 5.2.17 on 2026-09-28 08:00

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoSms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(max_length=16)),
                ("body", models.CharField(max_length=500)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
            ],
            options={
                "db_table": "demo_sms",
                "indexes": [
                    models.Index(fields=["phone", "-created_at"], name="demo_sms_phone_idx")
                ],
            },
        ),
    ]
