# Generated by Django 5.2.17 on 2026-09-28 07:24

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models

import apps.common.ids
from apps.common.migration_ops import CreatePartitionedModel


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("directory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=apps.common.ids.uuid7, editable=False, unique=True),
                ),
                (
                    "tracking_no",
                    models.CharField(blank=True, max_length=13, null=True, unique=True),
                ),
                ("beneficiary_name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "beneficiary_relation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SPOUSE", "Spouse"),
                            ("CHILD", "Child"),
                            ("PARENT", "Parent"),
                            ("SIBLING", "Sibling"),
                            ("OTHER", "Other"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("assisted", models.BooleanField(default=False)),
                ("owner_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=5000)),
                ("content_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Low"), (2, "Normal"), (3, "High"), (4, "Urgent")], default=2
                    ),
                ),
                ("citizen_urgent", models.BooleanField(default=False)),
                ("urgency_reason", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("AWAITING_CITIZEN", "Awaiting Citizen"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("reopen_deadline", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.CharField(blank=True, max_length=5000, null=True)),
                (
                    "rejection_reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INCOMPLETE", "Incomplete"),
                            ("NOT_ELIGIBLE", "Not Eligible"),
                            ("DUPLICATE", "Duplicate"),
                            ("WRONG_OFFICE", "Wrong Office"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("rejection_note", models.CharField(blank=True, max_length=5000, null=True)),
                ("info_request_count", models.PositiveSmallIntegerField(default=0)),
                ("reopen_count", models.PositiveSmallIntegerField(default=0)),
                ("reassignment_count", models.PositiveSmallIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="directory.category",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="directory.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "service_request",
            },
        ),
        CreatePartitionedModel(
            name="RequestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_role", models.CharField(blank=True, max_length=8, null=True)),
                ("event_type", models.CharField(max_length=32)),
                ("from_status", models.CharField(blank=True, max_length=16, null=True)),
                ("to_status", models.CharField(blank=True, max_length=16, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="service_requests.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "request_event",
            },
        ),
        migrations.CreateModel(
            name="SlaPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("MISSING_DOCUMENT", "Missing Document"),
                            ("UNCLEAR_REQUEST", "Unclear Request"),
                            ("VERIFICATION", "Verification"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pauses",
                        to="service_requests.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "sla_pause",
            },
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["owner", "-created_at", "-id"], name="sr_owner_created_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                condition=models.Q(("status", "SUBMITTED")),
                fields=["department", "-priority", "due_at", "submitted_at"],
                name="sr_dept_queue_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                condition=models.Q(("status__in", ["ASSIGNED", "IN_PROGRESS", "AWAITING_CITIZEN"])),
                fields=["assigned_officer", "status"],
                name="sr_officer_workload_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                condition=models.Q(
                    ("status__in", ["SUBMITTED", "ASSIGNED", "IN_PROGRESS", "AWAITING_CITIZEN"])
                ),
                fields=["due_at"],
                name="sr_open_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["owner", "content_hash", "-submitted_at"], name="sr_duplicate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                condition=models.Q(("assisted", True)),
                fields=["owner", "submitted_at"],
                name="sr_assisted_owner_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                condition=models.Q(("assisted", True)),
                fields=["submitted_by", "submitted_at"],
                name="sr_assisted_officer_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(fields=["department", "submitted_at"], name="sr_dept_submitted_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["category", "submitted_at"], name="sr_category_submitted_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "DRAFT",
                            "SUBMITTED",
                            "ASSIGNED",
                            "IN_PROGRESS",
                            "AWAITING_CITIZEN",
                            "RESOLVED",
                            "REJECTED",
                            "WITHDRAWN",
                        ],
                    )
                ),
                name="service_request_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("beneficiary_relation__in", ["SPOUSE", "CHILD", "PARENT", "SIBLING", "OTHER"])
                ),
                name="service_request_beneficiary_relation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "rejection_reason_code__in",
                        ["INCOMPLETE", "NOT_ELIGIBLE", "DUPLICATE", "WRONG_OFFICE", "OTHER"],
                    )
                ),
                name="service_request_rejection_reason_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", [1, 2, 3, 4])),
                name="service_request_priority_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("tracking_no__regex", "^[0-9]{2}-[0-9]{7,8}-[0-9]$")),
                name="service_request_tracking_no_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "DRAFT"),
                    models.Q(
                        ("due_at__isnull", False),
                        ("submitted_at__isnull", False),
                        ("tracking_no__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="service_request_submitted_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["ASSIGNED", "IN_PROGRESS", "AWAITING_CITIZEN"]),
                        _negated=True,
                    ),
                    ("assigned_officer__isnull", False),
                    _connector="OR",
                ),
                name="service_request_assigned_has_officer",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "RESOLVED"), _negated=True),
                    models.Q(("resolution_note__isnull", False), ("resolved_at__isnull", False)),
                    _connector="OR",
                ),
                name="service_request_resolved_has_note",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "REJECTED"), _negated=True),
                    ("rejection_reason_code__isnull", False),
                    _connector="OR",
                ),
                name="service_request_rejected_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("citizen_urgent", False), ("urgency_reason__isnull", False), _connector="OR"
                ),
                name="service_request_urgent_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("assisted", False),
                    models.Q(("submitted_by", models.F("owner")), _negated=True),
                    _connector="OR",
                ),
                name="service_request_assisted_by_other",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("beneficiary_name__isnull", True), ("beneficiary_relation__isnull", True)
                    ),
                    models.Q(
                        ("beneficiary_name__isnull", False), ("beneficiary_relation__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="service_request_beneficiary_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("info_request_count__lte", 3)),
                name="service_request_info_requests_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("reopen_count__lte", 2)), name="service_request_reopens_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_at__isnull", True),
                    ("due_at__gte", models.F("submitted_at")),
                    _connector="OR",
                ),
                name="service_request_due_after_submit",
            ),
        ),
        migrations.AddIndex(
            model_name="requestevent",
            index=models.Index(fields=["request", "created_at"], name="request_event_request_idx"),
        ),
        migrations.AddIndex(
            model_name="slapause",
            index=models.Index(fields=["request", "started_at"], name="sla_pause_request_idx"),
        ),
        migrations.AddConstraint(
            model_name="slapause",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reason_code__in",
                        ["MISSING_DOCUMENT", "UNCLEAR_REQUEST", "VERIFICATION", "OTHER"],
                    )
                ),
                name="sla_pause_reason_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="slapause",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_at__isnull", True),
                    ("ended_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="sla_pause_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="slapause",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("request",),
                name="sla_pause_one_open",
            ),
        ),
    ]
