# Generated by Django 5.2.17 on 2026-09-28 11:12

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models

import apps.common.ids


class Migration(migrations.Migration):
    dependencies = [
        ("service_requests", "0002_sla_cycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=apps.common.ids.uuid7, editable=False, unique=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("LATE_REJECTION", "Late Rejection"), ("SAMPLE", "Sample")],
                        max_length=16,
                    ),
                ),
                (
                    "decided_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("AWAITING_CITIZEN", "Awaiting Citizen"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UPHELD", "Upheld"),
                            ("OVERTURNED", "Overturned"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=2000, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="service_requests.servicerequest",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "request_review",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "PENDING")),
                        fields=["created_at"],
                        name="request_review_pending_idx",
                    ),
                    models.Index(fields=["request"], name="request_review_request_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("reason__in", ["LATE_REJECTION", "SAMPLE"])),
                        name="request_review_reason_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["PENDING", "UPHELD", "OVERTURNED"])),
                        name="request_review_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "PENDING"),
                            models.Q(("reviewed_at__isnull", False), ("reviewer__isnull", False)),
                            _connector="OR",
                        ),
                        name="request_review_decided_has_reviewer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "OVERTURNED"), _negated=True),
                            ("note__isnull", False),
                            _connector="OR",
                        ),
                        name="request_review_overturn_explained",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reviewer__isnull", True),
                            models.Q(("reviewer", models.F("officer")), _negated=True),
                            _connector="OR",
                        ),
                        name="request_review_no_self_review",
                    ),
                ],
            },
        ),
    ]
