# Generated by Django 5.2.17 on 2026-09-28 07:24

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name_bn", models.CharField(max_length=120)),
                ("name_en", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
            ],
            options={
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("name_bn", models.CharField(max_length=120)),
                ("name_en", models.CharField(max_length=120)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "holiday",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name_bn", models.CharField(max_length=120)),
                ("name_en", models.CharField(max_length=120)),
                ("target_working_days", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to="directory.department",
                    ),
                ),
            ],
            options={
                "db_table": "category",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("target_working_days__gt", 0)),
                        name="category_target_days_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SlaSuspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("reason", models.CharField(max_length=500)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scope_department",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        help_text="Empty means national.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="directory.department",
                    ),
                ),
            ],
            options={
                "db_table": "sla_suspension",
                "indexes": [
                    models.Index(fields=["starts_on", "ends_on"], name="sla_suspension_range_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                        name="sla_suspension_range_valid",
                    )
                ],
            },
        ),
    ]
