# Generated by Django 5.2.17 on 2026-09-28 07:24

import django.db.models.functions.datetime
from django.db import migrations, models

import apps.accounts.models
import apps.common.ids


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "public_id",
                    models.UUIDField(default=apps.common.ids.uuid7, editable=False, unique=True),
                ),
                ("phone", models.CharField(max_length=16, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("full_name", models.CharField(max_length=120)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("bn", "Bn"), ("en", "En")], default="bn", max_length=2
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CITIZEN", "Citizen"),
                            ("OFFICER", "Officer"),
                            ("ADMIN", "Admin"),
                        ],
                        default="CITIZEN",
                        max_length=8,
                    ),
                ),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("token_version", models.PositiveIntegerField(default=0)),
                ("totp_secret_encrypted", models.CharField(blank=True, max_length=255, null=True)),
                ("totp_enabled_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "app_user",
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LoginThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("device_key", models.CharField(max_length=64)),
                ("failures", models.PositiveSmallIntegerField(default=0)),
                ("next_allowed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "login_throttle",
            },
        ),
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(max_length=16)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("VERIFY_PHONE", "Verify Phone"),
                            ("RESET_PASSWORD", "Reset Password"),
                            ("CHANGE_PHONE", "Change Phone"),
                            ("CONFIRM_OWNER", "Confirm Owner"),
                        ],
                        max_length=16,
                    ),
                ),
                ("code_hmac", models.CharField(max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
            ],
            options={
                "db_table": "otp_challenge",
            },
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
            ],
            options={
                "db_table": "recovery_code",
            },
        ),
        migrations.CreateModel(
            name="RefreshSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=apps.common.ids.uuid7, editable=False, unique=True),
                ),
                ("family_id", models.UUIDField()),
                ("device_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "trust_mode",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal"),
                            ("SHARED", "Shared"),
                            ("STAFF", "Staff"),
                        ],
                        max_length=8,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("idle_expires_at", models.DateTimeField()),
                ("absolute_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, default="", max_length=32)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(), editable=False
                    ),
                ),
            ],
            options={
                "db_table": "refresh_session",
            },
        ),
    ]
