# Generated by Django 5.2.17 on 2026-09-28 07:24

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="directory.department",
            ),
        ),
        migrations.AddField(
            model_name="loginthrottle",
            name="user",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="otpchallenge",
            index=models.Index(
                fields=["phone", "purpose", "-created_at"], name="otp_phone_purpose_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpchallenge",
            index=models.Index(fields=["expires_at"], name="otp_expires_idx"),
        ),
        migrations.AddConstraint(
            model_name="otpchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "purpose__in",
                        ["VERIFY_PHONE", "RESET_PASSWORD", "CHANGE_PHONE", "CONFIRM_OWNER"],
                    )
                ),
                name="otp_challenge_purpose_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="otpchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__lte", 5)), name="otp_challenge_attempts_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="otpchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="otp_challenge_expiry_after_creation",
            ),
        ),
        migrations.AddField(
            model_name="recoverycode",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recovery_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refreshsession",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.refreshsession",
            ),
        ),
        migrations.AddField(
            model_name="refreshsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["department", "role"], name="user_department_role_idx"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("phone__regex", "^\\+8801[0-9]{9}$")), name="user_phone_e164"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["CITIZEN", "OFFICER", "ADMIN"])),
                name="user_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("preferred_language__in", ["bn", "en"])),
                name="user_preferred_language_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "OFFICER"), _negated=True),
                    ("department__isnull", False),
                    _connector="OR",
                ),
                name="user_officer_has_department",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "ADMIN"), _negated=True),
                    ("totp_enabled_at__isnull", False),
                    ("is_active", False),
                    _connector="OR",
                ),
                name="user_active_admin_has_totp",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="user_email_lower_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="loginthrottle",
            constraint=models.UniqueConstraint(
                fields=("user", "device_key"), name="login_throttle_user_device"
            ),
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(fields=["family_id"], name="refresh_family_idx"),
        ),
        migrations.AddIndex(
            model_name="refreshsession",
            index=models.Index(fields=["absolute_expires_at"], name="refresh_expiry_idx"),
        ),
        migrations.AddConstraint(
            model_name="refreshsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("trust_mode__in", ["PERSONAL", "SHARED", "STAFF"])),
                name="refresh_session_trust_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="refreshsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("idle_expires_at__lte", models.F("absolute_expires_at"))),
                name="refresh_session_idle_within_absolute",
            ),
        ),
    ]
