# Generated by Django 5.2.17 on 2026-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshsession",
            name="mfa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_last_counter",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
